# Generated by Django 3.2.13 on 2022-04-18 08:06

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Artist',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=100)),
                ('last_name', models.CharField(max_length=100)),
                ('email', models.EmailField(max_length=250)),
                ('location', models.CharField(max_length=100)),
            ],
            options={
                'verbose_name': 'Artist',
                'verbose_name_plural': 'Artist',
                'managed': True,
            },
        ),
        migrations.CreateModel(
            name='Commedian',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=100)),
                ('last_name', models.CharField(max_length=100)),
                ('email', models.EmailField(max_length=250)),
                ('location', models.CharField(max_length=100)),
            ],
            options={
                'verbose_name': 'Commedian',
                'verbose_name_plural': 'Commedian',
                'managed': True,
            },
        ),
        migrations.CreateModel(
            name='Dj',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=100)),
                ('last_name', models.CharField(max_length=100)),
                ('email', models.EmailField(max_length=250)),
                ('location', models.CharField(max_length=100)),
            ],
            options={
                'verbose_name': 'Dj',
                'verbose_name_plural': 'Dj',
                'managed': True,
            },
        ),
        migrations.CreateModel(
            name='Producer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=100)),
                ('last_name', models.CharField(max_length=100)),
                ('email', models.EmailField(max_length=250)),
                ('location', models.CharField(max_length=100)),
            ],
            options={
                'verbose_name': 'Producer',
                'verbose_name_plural': 'Producer',
                'managed': True,
            },
        ),
    ]
